### PR TITLE
Fix Issue 372

### PR DESCRIPTION
**Pull request by cewing**
This PR is intended to fix the reported problem (Issue #372) that pagination in the search form for work party reports does not work properly.

As a fix for that issue, it is ready to merge, however, work on the issue has revealed other, non-critical issues.

@davisagli there's a pretty serious weakness in the `updateQuery` function in the `WPReportSearch` component (https://github.com/washingtontrails/vms/blob/master/src/vms/static/app/report.js#L995).  The function will not update existing filter values, but rather appends new values on to the end of the existing query URL.  As used here in the pagination, a URL is passed in which represents the new query all on its own.  This function will take that url and append new filter values for every value contained in the filter list for the search component.  This means that as you click individual page links, each click appends repeated query values to the end of the existing url.  

I think this particular function could be rewritten using the URL manipulation API of a package like [URL.js](https://github.com/ericf/urljs) or the node package [urijs](https://www.npmjs.com/package/urijs) so that it did a better job of properly assembling a correct filter from the existing choices and new values requested.  However, since that fix is beyond the scope of fixing this particular bug, I'm not ready to make the call for that fix on my own.

### CODE REVIEW

**Comment by cguardia** [comment]
@cewing we just added node's querystring (https://nodejs.org/api/querystring.html) for story 320. Maybe you can use that to parse the query string and update using js?

**Comment by cewing** [comment]
Yep, looking into adapting the changes made for the search.js facets to this.  thanks, @cguardia

**Comment by cewing** [comment]
@davisagli, @cguardia, at this point the facets for search are all working and pagination is working when facets have been selected.  All search parameters are preserved across page changes.  

However there are still some issues:

1.  selected facets and search parameters do not appear in the URL, so there's no support for the back button or for linking to a search.

2.  if you make a facet selection that returns no results, the facet form disappears and cannot be made to re-appear.  This prevents a user from changing the form to clear the bad selection and a page reload is the only option left to clear the search (and it, of course, clears the entire search)

Looking for pointers on fixing this.

**Comment by davisagli** [comment]
> selected facets and search parameters do not appear in the URL, so there's no support for the back button or for linking to a search.

To make this work you need to call pushState when the filters change, like the main search does here: https://github.com/washingtontrails/vms/blob/master/src/vms/static/app/search.js#L597

And you need to handle the popState event and make it update the filters, like the main search does here: 
https://github.com/washingtontrails/vms/blob/master/src/vms/static/app/search.js#L539
https://github.com/washingtontrails/vms/blob/master/src/vms/static/app/search.js#L552
https://github.com/washingtontrails/vms/blob/master/src/vms/static/app/search.js#L600

**Comment by davisagli** [comment]
> if you make a facet selection that returns no results, the facet form disappears and cannot be made to re-appear.

I think you just need to remove the conditional on this line so that it shows the filters regardless of whether there is data:
https://github.com/washingtontrails/vms/blob/master/src/vms/static/app/report.js#L1058

**Comment by cewing** [comment]
@davisagli, @cguardia: I would appreciate some eyes on this one.  It's a bit more complicated than I'd originally hoped, but I believe it now works correctly in all the scenarios I can think of.

**Pull request merged**
