### PR TITLE
Features/workparties banner

### PR DESCRIPTION
**Pull request by cguardia**

### CODE REVIEW

**Comment by davisagli** [comment]
Is there a corresponding PR for wta_buildout to add the vms-banner view?

I would like to load this on the client side so that the server isn't tied up waiting for a response from Plone. It should be pretty easy if you write a react component that uses utils.DataLoaderMixin...you just have to set 'url' in getInitialState, and then it'll set this.state.data once the response is received. You probably also need to do self.request.response.setHeader('Access-Control-Allow-Origin', '*') in the Plone view so it can be loaded cross-domain.

**Comment by davisagli** [comment]
Also, the tests broke.

**Comment by cguardia** [comment]
@davisagli I committed the plone side changes to mybackpack-buildout directly. I thought it safe, given that it's just an extra view with no side effects for the rest of the code. I'll try to change the vms part to what you describe above.

**Comment by cguardia** [comment]
@davisagli made the component. Seems to work, but not sure about the test failures, as I didn't modify the workparty registration.

**Comment by davisagli** [comment]
I changed a couple things in the Plone changeset:
- get banners from /volunteers/vms-banners by default rather than /vms-banners
- sort by effective date rather than modified date

**Comment by davisagli** [comment]
Looks good, I merged and deployed and set up an example banner. Can you add testing instructions to the story and mark it as reviewing?

**Pull request merged**
