### PR TITLE
WIP: Issues/211

### PR DESCRIPTION
**Pull request by cguardia**
Making a PR for sanity checking.

### CODE REVIEW

**Comment by davisagli** [comment]
@cguardia can you please fix the failing tests? You probably need to update the fake_wp fixture in conftest.py

**Comment by cguardia** [comment]
Yeah, this is not finished yet. Will ping you when it's all green.

**Comment by davisagli** [comment]
Oh right, I overlooked the "WIP"

**Comment by cguardia** [comment]
@davisagli green, at last. If you can take a look later and think about any places I missed, that would be great.

**Comment by davisagli** [comment]
I fixed a few more.

The ticket says the end date/time should only be shown if it's on a different day than the start. Can you fix that? Actually I think we may want the end/date time on the full view of a single work party, but in the search results it'll make it easier to scan if we only show the end day when it's different.

**Pull request merged**
