### PR TITLE
Timezone issues in js and Python

### PR DESCRIPTION
**Pull request by cewing**
This pull request addresses issues #233 and #234, which arise from inconsistencies in the handling of timezone data across the VMS app (in javascript and Python).

The goal of these changes is to ensure that the date and time for work parties are presented in Pacific Time (using the timezone identifier `America/Los_Angeles`) regardless of the timezone in which the viewer is located.  

One aspect of the change forces times to be rendered in `America/Los_Angeles` by the `moment.js` library, using a new dependency [`moment-timezone`](http://momentjs.com/timezone/).  This dependency has been added to the deps listing for our js bundler, but I'd appreciate @davisagli having a look to see if there are any places I could add the dependency that would handle installing it for developers machines locally (I had to `npm install moment-timezone` on my local machine for `gulp` to work properly).

The second aspect of the change converts the `start_date_time` and `end_date_time` values of the stored data for work parties in elasticsearch to `America/Los_Angeles` in Python when the Python `WorkParty` object is created.  This means we can continue simply to display these values in templates without needing to convert them there.  An alternative approach would be to put the conversion logic into a template filter, assuming chameleon supports such things, but this seems simpler and since the data is not sent back to SF, appears to be free of side-effects.  Again, careful review by @davisagli would be deeply appreciated.

### CODE REVIEW

**Comment by cewing** [comment]
I believe the build error is related to my request for a review of the new js dependency.

**Comment by davisagli** [comment]
Declare the moment-timezone dependency in `package.json`. Then running buildout will install it when the `npm-install` buildout part runs npm install.  If you do npm install --save moment-timezone the --save option should take care of updating package.json for you.

**Comment by davisagli** [comment]
There are some real test failures too. I can take a closer look.

**Comment by cewing** [comment]
Thanks for these fixes, @davisagli!  I knew there would be something I missed.  Glad for the review.

**Pull request merged**
