### PR TITLE
Features/award confirmation

### PR DESCRIPTION
**Pull request by cguardia**

### CODE REVIEW

**Comment by davisagli** [comment]
This isn't quite doing the right thing. It's currently displaying a list of all awards available in the system. It's supposed to show a list of one checkbox for every award that has been earned by a person (i.e. one for every Participant Award). It should look like this:

[ ] David Glick - Hard Hat
[ ] Matthew Scholtz - Hard Hat
[ ] Carlos de la Guardia - Vest

where each of those is a participant awards related to a registrations in this work party. This is the leader's chance to report which awards were delivered (maybe the leader delivered my hard hat but could not deliver Matthew's because he was sick and was a no-show).

For each one that is checked, we should update the corresponding Participant Award to set its status to Awarded and its Date_Awarded__c field to today's date.

**Comment by cguardia** [comment]
I thought names didn't go in the report. Should I capture this similarly to volunteer hours?

**Comment by davisagli** [comment]
I'm not sure if the names need to be shown when looking at a previously submitted report, or not. But when filling out the report we definitely need to let the leader indicate which specific awards were delivered to which people, not just a general "yeah I delivered some hats"

**Comment by cguardia** [comment]
Fixed the feature.

**Comment by davisagli** [comment]
Thanks! I made a few fixes; the report form was no longer submitting for work parties with only one trail segment because of the validateInvariants check.

**Pull request merged**
